spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource  # Configuración específica de Tomcat JDBC
    tomcat:
      initial-size: 5
      max-active: 20
      max-idle: 5
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # Actualización de la clave de configuración
    defer-datasource-initialization: true
